train_path: "/Users/sinamalakouti/PycharmProjects/vilbert-multi-task/data/discoursedata/train"
test_path: "/Users/sinamalakouti/PycharmProjects/vilbert-multi-task/data/discoursedata/train"
n_epochs: 20
lr: 0.0001
batch_size: 32